// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type Mutation struct {
}

type NewUser struct {
	Fullname    string  `json:"fullname"`
	Phonenumber string  `json:"phonenumber"`
	Email       *string `json:"email,omitempty"`
}

type Query struct {
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Status  string `json:"status"`
	Message string `json:"message"`
}
