// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph_model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewTodoSecond struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
	User   User   `json:"user"`
	Status string `json:"status"`
}

type TodoSecond struct {
	ID     string     `json:"id"`
	Text   string     `json:"text"`
	Done   bool       `json:"done"`
	User   UserSecond `json:"user"`
	Status string     `json:"status"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserSecond struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
