package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/private-project-pp/graphql-api-service/model/graph_model"
)

// CreateTodoSecond is the resolver for the createTodoSecond field.
func (r *mutationResolver) CreateTodoSecond(ctx context.Context, input graph_model.NewTodoSecond) (*graph_model.TodoSecond, error) {
	panic(fmt.Errorf("not implemented: CreateTodoSecond - createTodoSecond"))
}

// TodosSecond is the resolver for the todosSecond field.
func (r *queryResolver) TodosSecond(ctx context.Context) ([]*graph_model.TodoSecond, error) {
	panic(fmt.Errorf("not implemented: TodosSecond - todosSecond"))
}
