package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/private-project-pp/graphql-api-service/interfaces/graph_server"
)

// Graph is the resolver for the graph field.
func (r *mutationResolver) Graph(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Graph - graph"))
}

// Graph is the resolver for the graph field.
func (r *queryResolver) Graph(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: Graph - graph"))
}

// Mutation returns graph_server.MutationResolver implementation.
func (r *Resolver) Mutation() graph_server.MutationResolver { return &mutationResolver{r} }

// Query returns graph_server.QueryResolver implementation.
func (r *Resolver) Query() graph_server.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
