package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/private-project-pp/graphql-api-service/model/graph_model"
)

// UpsertUser is the resolver for the upsertUser field.
func (r *mutationResolver) UpsertUser(ctx context.Context, input graph_model.UpsertUser) (*graph_model.User, error) {
	panic(fmt.Errorf("not implemented: UpsertUser - upsertUser"))
}
