package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"

	"github.com/private-project-pp/graphql-api-service/model/graph_model"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context) (*graph_model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}
